Homework for Lesson 7
filkodaria/js_hw pull request #5
Opened 2024-06-07 21:07 UTC by filkodaria

Homework_7: task_1, task_2, task_3.

2024-06-08 13:26 UTC, VladimirLQA requested changes

2024-06-08 13:26 UTC, VladimirLQA commented on hw_7/hw_7.1.js
> +	}
```suggestion
	}
     const result = arrayOnAnyValues.filter(el => typeof el === 'number' && !isNaN(el));
      return result; 
```

2024-06-08 13:26 UTC, VladimirLQA commented on hw_7/hw_7.2.js
> +			if (el.charCodeAt(0) >= 97 && el.charCodeAt(0) <= 122) {
```js
  if(el.match(/[a-z]/g))
````

2024-06-08 13:26 UTC, VladimirLQA commented on hw_7/hw_7.2.js
> +				for (let i = 0; i < arr.length; i++) {
Can use `.forEach` method for comparing chars

2024-06-08 13:26 UTC, VladimirLQA commented on hw_7/hw_7.2.js
> +}
Try to use `arrow` functions :)
```suggestion
const getTotalPrice = (arr) => arr.reduce((total, value) => total + value, 0);
```

2024-06-08 13:26 UTC, VladimirLQA commented on hw_7/hw_7.2.js
> +function sortArrayByVowels(arr) {
You can make that helper function will accept the string and return the count of vowels only
For example
```js
const countVowels = (str) => count;
const sortArrayByVowels = (arr) => [...arr].sort((a, b) => countVowels(a) - countVowels(b));
```

2024-06-08 13:26 UTC, VladimirLQA commented on hw_7/hw_7.2.js
> +		for (let i = 0; i < el.length; i++) {
Again we can use efficient array methods :)

2024-06-08 13:26 UTC, VladimirLQA commented on hw_7/hw_7.2.js
> +function checkBracketsPair(arr) {
Follow the task description
Try this example
```
const arr = [[['(']], ')', '(', ')', ')', ['(', ['('], [')']]]
```

2024-06-08 13:26 UTC, VladimirLQA commented on hw_7/hw_7.2.js
> +	if (!newString.length) {
Ternary operator

2024-06-08 13:26 UTC, VladimirLQA commented on hw_7/hw_7.3.js
> +function findMissingNumber(arr) {
Try to use efficient array methods :)

2024-06-10 20:23 UTC, filkodaria commented
@VladimirLQA 
please, check changes to tasks 7.1 and 7.2.

2024-06-10 20:36 UTC, anatoly-karpovich approved these changes

2024-06-10 20:36 UTC, anatoly-karpovich commented on hw_7/hw_7.2.js
> +}
```suggestion
function transformToAppearanceTimes(string) {
  if (typeof string !== "string") throw new Error("Argument must be a string");
  const abc = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
  return [...string].map((char, i, arr) => (abc.includes(char) ? arr.filter((c) => c === char).length : char)).join("");
}
```

2024-06-10 20:36 UTC, anatoly-karpovich commented on hw_7/hw_7.3.js
> +function findMissingNumber(arr) {
Agree with magister VoYoda)

2024-06-10 21:10 UTC, VladimirLQA approved these changes

2024-06-10 22:06 UTC, filkodaria commented
@VladimirLQA 
I've added changes to task 7.3 (subtask 5)
Check please

2024-06-11 14:00 UTC, VladimirLQA approved these changes

2024-06-11 14:20 UTC, merged

2024-06-11 14:21 UTC, filkodaria commented
Thank you guys for homework review!